# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.3.3
_src_path: gh:algorandfoundation/algokit-python-template
author_email: samyaklahire1306@gmail.com
author_name: samyak
contract_name: digital_marketplace
deployment_language: python
preset_name: production
project_name: digital_marketplace

